#
# Copyright (c) 2024 The C++ Alliance, Inc. (https://cppalliance.org)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Official repository: https://github.com/boostorg/website-v2-docs
#

# This configures Antora for building site docs
#
# website link structure:
#
# /libs/{name}                          Redirect to /{version}/lib/{name}
# /{version}/lib/{name}                 library docs
# /{version}/lib/user-guide             User Guide
# /doc/contributor-guide
# /doc/boost-formal-review
# /develop/doc/contributor-guide
# /develop/doc/boost-formal-review
#
# /doc/libs/{old-version}/libs/{name}   redirect to versioned legacy lib docs
#
# name:         library-name
# version:      "master" | "develop" | {semantic-version}
# old-version:  DIGIT+ '_' DIGIT+ '_' DIGIT+
#

site:
  url: https://boost.revsys.dev/
  title: Boost Site Docs
  start_page: user-guide::index.adoc

antora:
  extensions:
    - require: ./extensions/boost.js
asciidoc:
  attributes:
    page-pagination: ''
  extensions:
    - ./extensions/boost-link-inline-macro.js
    - '@asciidoctor/tabs'

content:
  sources:
    - url: https://github.com/boostorg/website-v2-docs
      start_path: user-guide
      edit_url: '{web_url}/edit/develop/{path}'
    - url: https://github.com/boostorg/website-v2-docs
      start_path: formal-reviews
      edit_url: '{web_url}/edit/develop/{path}'
    - url: https://github.com/boostorg/website-v2-docs
      start_path: contributor-guide
      edit_url: '{web_url}/edit/develop/{path}'

ui:
  bundle:
    # url: https://github.com/cppalliance/antora-ui/releases/download/ui-${page-boost-branch}/ui-bundle.zip
    url: ./antora-ui/build/ui-bundle.zip
    snapshot: true

output:
  dir: ./build

# https://docs.antora.org/antora/latest/playbook/runtime-log-failure-level/
runtime:
  log:
    failure_level: error
